version: '3.8'

services:
  ocr-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ocr-web-service
    ports:
      - "8000:8000"
    volumes:
      - ./input:/app/uploads  # 持久化上传目录
      - ./config:/app/config:ro   # 配置文件挂载
    environment:
      - OCR_ARGS=-l eng+fra+chi_sim --rotate-pages --deskew --jobs 4 --output-type pdfa
      - MAX_FILE_SIZE=104857600  # 100MB
      - UVICORN_WORKERS=2
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ocr_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/ocr_uploads  # 宿主机存储路径

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24